config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get 'dashboard', to: "dashboard#index", as: 'dashboard'
  get 'purchase_orders/:id', to: "purchase_orders#show", as: 'purchase_order'
#reroute id path to show controllers, extra convenience method for path

  devise_for :users, :controllers => {:registrations => "registrations"}
  devise_scope :user do
    get 'start', to: "registrations#start", as: 'start'
    get 'signup', to: "registrations#new", as: 'signup'
    get 'login', to: "sessions#new", as: 'login'
    get 'settings', to: "registrations#edit", as: 'settings'
    delete 'logout', to: "sessions#destroy", as: 'logout'
  end

end

app/views/shared/_footer.html.erb
<div class="footer" style="text-align:center" id="footer">
  <!-- your footer content -->
</div>

<!-- google analytics -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  
  // your property code 
  ga('create', 'UA-XXXXXXXXXX', 'auto');
  ga('send', 'pageview');

</script> 

app/views/shared/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header-collapse" role="navigation">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to (image_tag "logo.png", alt: "Job Tracker", class: "navbar-brand"), root_path %>
    </div>

    <div class="collapse navbar-collapse" id="navbar-collapse" data-toggle="Collapse" data-target=".navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
        <li><%= link_to "Settings", settings_path %></li>
        <li><%= link_to "Logout", logout_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Login", login_path %></li>
        <li><%= link_to "Signup", signup_path %></li>
      <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>